# 全局配置
server:
  port: 9092

spring:
  application:
    name: read-service
  profiles:
    active: dev
  cloud:
    # 服务提供方
    consul:
      discovery:
        # 启用服务发现(因为是服务提供方，无需开启服务发现)
        # enabled: true
        # 将服务注册到consul
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 注册成功后的唯一标识
        instance-id: ${spring.application.name}
        # 注册成功后的服务名称(服务间调用使用此名称)
        service-name: ${spring.application.name}-001
      host: 127.0.0.1
      port: 8500

# mybatis集成
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




